# Generated by Django 5.0.7 on 2024-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('reviewContent', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_At', models.DateField()),
                ('rewiever_emil_Id', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('NotPublished', 'NotPublished')], max_length=100)),
                ('genres', models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'comedy'), ('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Triller', 'Triller')], max_length=100)),
            ],
        ),
    ]
