# Generated by Django 5.0.7 on 2024-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_review',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie_review',
            name='genres',
            field=models.ManyToManyField(to='reviewapp.genres'),
        ),
    ]
