# Generated by Django 5.0.7 on 2024-08-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_genres_remove_movie_review_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genres',
            old_name='genres',
            new_name='name',
        ),
    ]
