# Generated by Django 5.0.7 on 2024-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0005_alter_movie_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='created_At',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='genres',
            field=models.ManyToManyField(choices=[('Horror', 'Horror'), ('Comedy', 'comedy'), ('Action', 'Action'), ('Sci-Fi', 'Sci-Fi'), ('Triller', 'Triller')], to='reviewapp.genre'),
        ),
    ]
